### ISSUE TITLE
Add Page Editor support for control flow bricks

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#3491]
## Context
- https://github.com/pixiebrix/pixiebrix-extension/pull/3454 added bricks for if-else, try-catch, and for-each
- These each have one or two properties that take a pipeline expression
- The try-catch/for-each brick also exposes arguments for supplying a key for the error and loop element variable respectively. The defaults are `@error` and `@element`

## Implementation Sketch
- [x] Update [withInstanceIds](https://github.com/pixiebrix/pixiebrix-extension/blob/4ba9771e3d6d8c3d32557abdc6db3a6bec0a15e9/src/pageEditor/extensionPoints/base.ts#L99-L99) to recursively assign instance ids to pipeline bricks
- [x] Update [omitMetadata](https://github.com/pixiebrix/pixiebrix-extension/blob/4ba9771e3d6d8c3d32557abdc6db3a6bec0a15e9/src/pageEditor/extensionPoints/base.ts#L109-L109) to remove instanceIds from bricks
- [x] Show sub-entries in the extension overview for each pipeline argument of a brick. Show: 1) the name based on the property name/title in the JSON Schema, 2) a key based on what the user has configured #3540 
- [x] Enable operations on the sub-pipeline: 1) add brick, 2) remove #3590 
- [x] Enable selecting the brick to configure it #3540
- [x] Enable re-order (should not move across the boundary)
- [x] Enable copy-paste #3631 
- [ ] Compute `relevantBlocksToAdd` for the subpipeline independently (see `BrickModal.tsx`)
- [ ] Test the Add and Remove actions of the root pipeline and sub pipelines
- [ ] Test the re-ordering of the bricks within the root pipeline and sub pipelines
- [ ] Refactor traversing the pipeline and generation of nodes
- [ ] Re-use selectors in reducers (EditorSlice). Maybe use thunk for the editor slice.
- [ ] Refactor validation in the [usePipelineField](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/pageEditor/hooks/usePipelineField.ts#L48)
- [ ] [Data Panel.](https://github.com/pixiebrix/pixiebrix-extension/blob/51b71f0bc59a1b56e28fa0ab784b8d99635a0e88/src/pageEditor/tabs/editTab/dataPanel/DataPanel.tsx#L94) Context and Input. For sub pipeline bricks check the parent pipelines for the changes to show warnings about stale data.

## Assumptions
- We can hard-code some logic/mappings in for these 3 bricks for now where it makes sense. We don't need to support arbitrary bricks that support pipeline expressions yet. (Pipeline expressions are only possible to execute from JS bricks...)

## Considerations
- This does not have to be done as a single PR. E.g., re-ordering bricks in a sub-pipeline is nice to have
- Let's prioritize the bricks in this order: 1) for-each, 2) if-else, 3) try-catch
- There's a ticket here: https://github.com/pixiebrix/pixiebrix-extension/issues/3492 to generate the trace information for the bricks by instanceId

## Out of Scope
- Document Builder

## Wireframes
![image](https://user-images.githubusercontent.com/1879821/170397236-d3c362ef-d72d-4b47-9946-75aa62062596.png)
