### ISSUE TITLE
Add support for Firefox

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#36]
**References:** 
- https://github.com/mozilla/web-ext
- https://extensionworkshop.com/documentation/publish/submitting-an-add-on/

Firefox does not support extenally_connectable yet, so need a different way to exchange the token. Discussion:
- https://bugzilla.mozilla.org/show_bug.cgi?id=1319168
- https://discourse.mozilla.org/t/using-runtime-sendmessage-api-from-webpages/36984

**Subtasks:**

- [x] Split webpack configs and add Firefox manifest
- [x] Remove dependency on extenally_connectable
- [x] Code splitting because Mozilla upload/signing only supports modules < 4mb. See https://github.com/pixiebrix/pixiebrix-extension/issues/95
