### ISSUE TITLE
Deal with context invalidation in the sidebar (notify user, reload?)

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#4115]
When the extension is reloaded, all pages stop receiving messages, including any sidebars currently on the page. This is not immediately visible and will result into failed retries of SIDEBAR_RENDER_PANELS towards the attached sidebar, which is visible but cannot receive messages.

## Tasks

- [x] Notify user of context invalidation [#4117](https://github.com/pixiebrix/pixiebrix-extension/pull/4117)
- [ ] Adapt `ErrorBanner` to work in the sidebar instead of using a notification 
- [ ] When messaging the sidebar, detect this state and suggest reloading it? We should probably not automatically reload it to avoid user data loss (e.g. while filling a form)
