### ISSUE TITLE
[epic] Page Editor performance review

### ISSUE THREAD

**Issue by BALEHOK** [pixiebrix/pixiebrix-extension#4949]
Investigation details: https://www.notion.so/pixiebrix/Page-Editor-performance-review-4fe0a3c4d6924a2ab0e9ff7b234d5f8b

Related issues:

- [x] #4950
- [x] #4958
- [x] Reduce the impact of Editor persistence on the application https://github.com/pixiebrix/pixiebrix-extension/pull/4992
- [x] https://github.com/pixiebrix/pixiebrix-extension/issues/4023
- [ ] https://github.com/pixiebrix/pixiebrix-extension/issues/4000
- [x] #3945
- [x] #3899
