### ISSUE TITLE
Refactor: rename typescript Types

### ISSUE THREAD

**Issue by mnholtz** [pixiebrix/pixiebrix-extension#5994]
Follow-up of https://github.com/pixiebrix/pixiebrix-extension/issues/5934

### Remaining Work

- [x] Cleanup references in comments to old type names
    - [x] `RecipeDefinition`
- [x] Rename `UnnormalizedRecipeDefiniton` -> `UnnormalizedModDefinition`
- [x] Rename `RegistryRecipeDefinition` -> `RegistryModDefinition`
- [x] [Rename `CloudExtension` -> `StandaloneModDefinition`](https://www.notion.so/pixiebrix/Proposal-Domain-Modelling-and-Naming-9f7c8ffc0ed4458599a67536d74bdc3a?pvs=4#4962f8e61de3478b8695e5811491edcf) 
- [ ] [Introduce the `ActivatedMod` type](https://www.notion.so/pixiebrix/Proposal-Domain-Modelling-and-Naming-9f7c8ffc0ed4458599a67536d74bdc3a?pvs=4#62c017f082954b73936c6d25952cdf7c)
- [x] [Rename `PersistedExtension` -> `ActivatedModComponent`](https://www.notion.so/pixiebrix/Proposal-Domain-Modelling-and-Naming-9f7c8ffc0ed4458599a67536d74bdc3a?pvs=4#ae88b14c0d524bef9a8bdfab25adc810)
- [x] [Rename `ExtensionDefinition` -> `ModComponentDefinition`](https://www.notion.so/pixiebrix/Proposal-Domain-Modelling-and-Naming-9f7c8ffc0ed4458599a67536d74bdc3a?pvs=4#507db5a1f4644cf08a8e89fc6186568a)
- [x] [Rename `ExtensionPointConfig` -> `StarterBrickConfig`](https://www.notion.so/pixiebrix/Proposal-Domain-Modelling-and-Naming-9f7c8ffc0ed4458599a67536d74bdc3a?pvs=4#d62f3c32ec28463d8ad876ccdab80326)
- [x] Rename `ExtensionPointDefinition` -> `StarterBrickDefinition`
- [x] Rename `ExtensionPointType` -> `StarterBrickType`
- [x] [Rename `ExtensionPoint` -> `StarterBrickABC`](https://www.notion.so/pixiebrix/Proposal-Domain-Modelling-and-Naming-9f7c8ffc0ed4458599a67536d74bdc3a?pvs=4#d29240a4c95a4b30afb50441af3e8957)
- [x] [Introduce brick-type implementations](https://www.notion.so/pixiebrix/Proposal-Domain-Modelling-and-Naming-9f7c8ffc0ed4458599a67536d74bdc3a?pvs=4#4acc284fed054e2e84f10b713317f6de)
    - `TransformerABC`
    - `EffectABC`
    - `RendererABC`
    - `ReaderABC`
- [x]  [Introduce `StarterBrickConfig`](https://www.notion.so/pixiebrix/Proposal-Domain-Modelling-and-Naming-9f7c8ffc0ed4458599a67536d74bdc3a?pvs=4#5ab5cc3d03cc40e4b519c6310ee676b4)
- [x]  Rename integration types: https://www.notion.so/pixiebrix/Proposal-Domain-Modelling-and-Naming-9f7c8ffc0ed4458599a67536d74bdc3a?pvs=4#b0168c45716241119431438a40dd6a23
- [x]  Rename registry types: https://www.notion.so/pixiebrix/Proposal-Domain-Modelling-and-Naming-9f7c8ffc0ed4458599a67536d74bdc3a?pvs=4#c7f141ae6b344f77b45b7daafe4e77a5
- [x]  Rename Page Editor types: https://www.notion.so/pixiebrix/Proposal-Domain-Modelling-and-Naming-9f7c8ffc0ed4458599a67536d74bdc3a?pvs=4#37bf242d5c9e47ff8aae06a0e3d6cd3c
- [x]  Rename `IBrick` -> `Metadata` https://www.notion.so/pixiebrix/Proposal-Domain-Modelling-and-Naming-9f7c8ffc0ed4458599a67536d74bdc3a?pvs=4#00a97421cdb64c5a86456f15ab301086
- [x]  Rename `IExtension` https://www.notion.so/pixiebrix/Proposal-Domain-Modelling-and-Naming-9f7c8ffc0ed4458599a67536d74bdc3a?pvs=4#98b9eda54cec4b168244a0b64d394445
- [x] Rename associated typeguards
- [x] Rename `extensionTypes.ts` -> `modComponentTypes.ts`
- [x] Rename `extensionPointTypes.ts` -> `starterBrickTypes.ts`
- [x] Rename `serviceTypes.ts` -> `integrationTypes.ts`
- [ ] Rename `localRegistry.ts` -> `packageRegistry.ts`
