### ISSUE TITLE
Incremental strictNullChecks adoption - Slice 1

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#6494]
### Find Candidates Result:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBajI3IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3ee761730a9da84b3098bbb1f2aea63539912da7/image.png)

### Tasks
- [x] Add the following files to `src/tsconfig.strictNullChecks.json`
  - [x] `./utils/stringUtils.ts`
  - [x] `./utils/objectUtils.ts`
  - [x] `./utils/promiseUtils.ts`
  - [x] `./utils/storageUtils.ts`
  - [x] `./utils/sanitize.ts`
- [x] Run `npm run build:strictNullChecks` to get list of errors
- [x] Fix errors
- [x] From `pixiebrix/strict-null-check-migration-tools`:
  - [x] Run `npm run find-candidates -- <your_project_path>/src/tsconfig.strictNullChecks.json`
- [x] Create Slice 2 issue from top five issues in `find-candidates` output
