### ISSUE TITLE
Incremental strictNullChecks adoption - Slice 2

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#6498]
### Find Candidates Result:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaExHIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2fcc327bc101c84f425c63cd72cfd0789ddcc087/image.png)

### Tasks
- [x] Add th following files to `src/tsconfig.strictNullChecks.json`
  - [x] `./errors/networkErrorHelpers.ts`
  - [x] `./utils/schemaUtils.ts`
  - [x] `./utils/urlUtils.ts`
  - [ ] `./contentScript/messenger/api.ts`
  - [x] `./store/migratePersistedState.ts`
- [x] Run `npm run build:strictNullChecks` to get list of errors
- [x] Fix errors
- [x] From `pixiebrix/strict-null-check-migration-tools`:
  - [x] Run `npm run find-candidates -- <your_project_path>/src/tsconfig.strictNullChecks.json`
- [ ] Create Slice 3 issue from top five issues in `find-candidates` output (top of Backlog on DX Board)
