### ISSUE TITLE
Incremental strict null checks adoption: Slice 3

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#6527]
### Tasks
- Add the following files to `src/tsconfig.strictNullChecks.json`
  - [x] `./utils/storageUtils.ts`
  - [x] `./components/annotationAlert/FieldAnnotationAlert.tsx`
  - [x] `./components/Loader.tsx`
  - [x] `./components/MarkdownInline.tsx`
  - [x] `./utils/variableUtils.ts`
  - [x] `./hooks/useEventListener.ts`
- [x] Run `npm run build:strictNullChecks` to get list of errors
- [x] Fix errors
- From `pixiebrix/strict-null-check-migration-tools`:
  - [ ] Run `npm run find-candidates -- <your_project_path>/src/tsconfig.strictNullChecks.json`
- [ ] Create Slice 4 issue from top five issues in `find-candidates` output (top of Backlog on DX Board)
