### ISSUE TITLE
Incremental strict null checks adoption: Slice 4

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#6537]
### Find Candidates Result:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb3JnIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9c0f3b7a61d5ddf9466a5eb11ba750f89fa3cd10/image.png)

### Tasks
- Add the following files to `src/tsconfig.strictNullChecks.json`
  - [x] `./errors/networkErrorHelpers.ts`
  - [x] `./utils/schemaUtils.ts`
  - [ ] `./bricks/transformers/tourStep/overlay.ts`
  - [ ] `./icons/list.ts`
  - [ ] `./utils/detectRandomString.ts`
- [ ] Run `npm run build:strictNullChecks` to get list of errors
- [ ] Fix errors
- From `pixiebrix/strict-null-check-migration-tools`:
  - [ ] Run `npm run find-candidates -- <your_project_path>/src/tsconfig.strictNullChecks.json`
- [ ] Create Slice 5 issue from top five issues in `find-candidates` output (top of Backlog on DX Board)

**Comment by fregante** [comment]
The first two are covered by #6525, I'll look for 2 more files before starting

**Comment by fregante** [comment]
By the way after this issue I think it might be easier to open issues with this content:

```md
1. From [pixiebrix/strict-null-check-migration-tools](https://github.com/pixiebrix/strict-null-check-migration-tools):
	- Run `npm run find-candidates -- <your_project_path>/src/tsconfig.strictNullChecks.json`
2. Add the first 5 files to `src/tsconfig.strictNullChecks.json`
	- Exclude the messenger, see #6526 
3. Run `npm run watch:strictNullChecks`
4. Fix every error (exclude files that cause more than 20 errors)
```

So whoever runs the migration tool can just look at the file list and work on it, rather than seeing duplicates, problematic files here
